import { Given, When, Then } from "@cucumber/cucumber";
import { Methods, sendRequest } from "../../common/helper.js";
import Cake from "../../../../src/domain/models/cake.model.js";
import assert from 'assert';
import { assertCake } from "../../common/cake.js";


Given('nama kue {string}', function (name) {
    this.reqBody = { name };
});

Given('harga {string}', function (price) {
    if (price.length > 0) {
        this.reqBody.price = parseInt(price);
    }
});

Given('kue dengan nama {string} dan harga {int} telah ditambahkan', async function (name, price) {
    await Cake.create({ name, price });
});

When('pengguna mengirimkan permintaan untuk membuat kue', async function () {
    this.response = await sendRequest("/api/v1/cakes", Methods.Post, this.reqBody, this.authHeader);
});

Then('pesan respons harus kue yang ditambahkan', function () {
    // Get the response body from the context (set by previous step)
    const responseBody = this.response.body;

    // Ensure the response body exists
    assert.ok(responseBody);

    // Extract the `cake` object from the response
    const cake = responseBody.cake;

    // Validate that the cake object exists
    assert.ok(cake);

    // Ensure the `id` field is present (auto-generated by backend)
    assert.ok(cake.id);

    // against the original request body to confirm correct persistence
    assertCake(cake, this.reqBody);
});
