name: Oishi Keki Pipeline

on:
  push:
    branches: ["main"] 
  pull_request:
    branches: ["main"]

jobs:
  sonarqube:
    name: SonarQube
    runs-on: ubuntu-latest
    if: github.event_name == 'pull_request'
    env:
      DOTENV_PRIVATE_KEY_TEST: ${{ secrets.DOTENV_PRIVATE_KEY_TEST }}
    services:
      postgres:
        image: postgres:17.5-alpine
        env:
          POSTGRES_USER: ${{ vars.POSTGRES_USER }}
          POSTGRES_PASSWORD: ${{ secrets.POSTGRES_PASSWORD }}
          POSTGRES_DB: ${{ vars.POSTGRES_DB }}
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0  # Shallow clones should be disabled for a better relevancy of analysis

      - name: Setup Node.js
        uses: actions/setup-node@v4

      - name: Install dependencies
        run: npm ci

      - name: Install sequelize cli
        run: npm install --save-dev sequelize-cli

      - name: Migrate database
        run: npm run migrate:test:up

      - name: Install c8
        run: npm install c8

      - name: Run unit tests
        run: npm run test:unit

      - name: Run BDD test
        run: npx c8 -r lcov npm run test:bdd

      - name: SonarQube Scan
        uses: SonarSource/sonarqube-scan-action@v5
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}